# Generated by Django 3.2.7 on 2024-08-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArriendoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propiedad',
            name='comuna',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='tipo_inmueble',
        ),
    ]
